version: "3"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ecommerce_backend
    restart: always
    env_file:
      - .env
    ports:
      - "4001:4000"
    volumes:
      - ../file_bucket:/usr/src/file_bucket:rw
  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
  #   depends_on:
  #     - mongo
  # mongo:
  #   container_name: mongo
  #   image: mongo:4.4.6
  #   restart: always
  #   environment:
  #     - MONGO_INITDB_DATABASE=main
  #     - MONGO_INITDB_ROOT_USERNAME=admin
  #     - MONGO_INITDB_ROOT_PASSWORD=hellobro
  #   ports:
  #     - "27017:27017"
